import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import MainHeader from "@/component/main-header/main-header";
import MainHeaderBackgroud from "@/component/main-header/main-header-backgroud";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body>

        <MainHeader/>
        {children}
        </body>
        </html>
    );
}
